### ISSUE TITLE
blocking identities

### ISSUE THREAD

**Issue by basvandervlies** [SURFnet/tiqr-client-ios#40]
I have multiple identities on my TIQR app. Now if I enter the wrong pin code for one of my identities and the return code is:
 * `INVALID_RESPONSE:0`

Not the failing identity is blocked, but all the  identities are blocked. Is this a bug or the normal behaviour?

**Comment by joostd** [comment]
That’s intended behaviour. Although every tiqr credential can have a unique key, we expect most users to use the same PIN for all credentials. When multiple credentials are used, an attacker has as many more tries in a brute force attack against the user PIN and thus against the encryption key for all tiqr secrets stored on the phone.

If this is a problem, we advice to either use throttling (with a back off mechanism) and/or advice users to enable biometrics to protect the tiqr secrets.

**Comment by basvandervlies** [comment]
Thanks for the explanation it makes sense.  When we use the biometrics in the enrollment process we get:
```
Account can not be saved
Failed to generate identity secret. Pleas contact support
```

Only the PIN mode works for us

**Comment by joostd** [comment]
That’s odd. What is your iPhone model?

**Comment by basvandervlies** [comment]
I have an iPhone 8 and my colleagues that test the TIQR app have the same problem

**Comment by joostd** [comment]
I don’t have any problems with an iPhone8. Are you using the [php library](https://github.com/SURFnet/tiqr-server-libphp) or have you implemented the [tiqr protocol](https://github.com/SURFnet/tiqr/wiki/Protocol-documentation) yourself?

Do you also experience these problems on the [tiqr demo site](https://demo.tiqr.org/v1/securelogin.php)?

**Comment by basvandervlies** [comment]
We use privacyidea that implemented the TIQR protocol in python.   We have implemented some enhancements to the TIQR protocol in privacyidea for the enrollment process.  I just tested the enrolment process and the biometrics works for me. Does the biometrics implementation require some metadata present?

I will test it tomorrow with some other users and see what happens.

**Comment by joostd** [comment]
There shouldn't be any difference in the server (and hence in metadata) between using biometrics or PIN on the client. 

The only difference is whether the secret is protected by encrypting with a symmetric key derived from a PIN or additionally using the phone’s hardware Secure Enclave protected using biometrics.

**Comment by basvandervlies** [comment]
We are testing the app a lot and delete the accounts frequently.  As told yesterday I could enrol with biometrics and my colleagues also.  But after deleting the accounts and starting the enrolment again it fails with biometrics for all of us (different iphone 8's). So it looks like a cache problem or to frequently accessing the biometrics interface.

**Comment by joostd** [comment]
Please note that account parameters (like authentication endpoint or ocra suite) are not stored per account but per authentication server.

This means that changing these parameters does not have any effect as long as there are other accounts existing on the client with the old parameters.

Does removing all accounts for that server and registering a new one solve the problem?

**Comment by basvandervlies** [comment]
> Does removing all accounts for that server and registering a new one solve the problem?

No just tried it and also deleting the app and reinstalling it again does not fix the problem.

**Comment by joostd** [comment]
Hm, weird. If biometrics do work in the tiqr demo but not with privacyidea, there must be some difference between the two.

Maybe we can ask @cornelinux if he has experienced anything similar?

**Comment by cornelinux** [comment]
I have no bio-tiqr. Is bio supposed to work on android?

**Comment by joostd** [comment]
Yes, provided you have an android device with a fingerprint scanner and have upgraded to tiqr version 3.

**Comment by basvandervlies** [comment]
The problem is that we enrol account for the first time on the server and APP it works. But if we remove the account in the TIQR app and the TIQR token on the server and enrol again it fails.

**Comment by joostd** [comment]
Hm, that sounds like a client problem then. I’ll ask an iOS develop to have a look.

**Comment by Jaapdijkshoorn** [comment]
We see in console logs of iphone this:
`
insert failed for item <genp,rowid=null,cdat=2019-08-13 16:35:26 +0000,mdat=2019-08-13 16:35:26 +0000,desc=null,icmt=null,crtr=null,type=null,scrp=null,labl=null,alis=null,invi=null,nega=null,cusi=null,prot=null,acct=jaap_2fa-biometric,svce=nl.surf,gena=null,data=07bf:070000000AF7040A...|ec72123c328bfbfa,agrp=8N8BAGUPCC.nl.surfsara.tiqr,pdmn=ak,sync=0,tomb=0,sha1=95C233C672FC8C49FB582A57D648095E4621900A,vwht=null,tkid=null,v_Data=<?>,v_pk=29A2097022F80D1193B672BA1C000F6F43772A9D,accc=null,u_Tomb=null,musr=,UUID=6BEB51E3-D0AB-45D5-B720-17478ACCDCA1,sysb=null,pcss=null,pcsk=null,pcsi=null,persistref=> with Error Domain=com.apple.utilities.sqlite3 Code=19 "finalize: 0x1052497a0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr" UserInfo={NSDescription=finalize: 0x1052497a0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr, NSUnderlyingError=0x100e02170 {Error Domain=com.apple.utilities.sqlite3 Code=
`
`
Example[1234]/1#4 LF=0 add Error Domain=NSOSStatusErrorDomain Code=-25299 "duplicate item O,genp,29A20970,L,ak,8N8BAGUPCC.nl.surfsara.tiqr,0,acct,svce,v_Data,musr,20190813163526.189729Z,95C233C6" UserInfo={NSDescription=duplicate item O,genp,29A20970,L,ak,8N8BAGUPCC.nl.surfsara.tiqr,0,acct,svce,v_Data,musr,20190813163526.189729Z,95C233C6}
`

duplicate items?

**Comment by joostd** [comment]
Can you post some examples of tiqrenrol:// URIs embedded in the QR codes? Together with the resolved metadata, i.e. the URI converted into a URL by replacing tiqrenrol with https and then retrieved with curl or something?

You may want to wait for the metadata to expire or obfuscate the enrollment secret if you do not want that information to appear on github for eternity.

**Comment by martijnkruiten** [comment]
tiqrenroll://https://2fa.surfsara.nl/ttype/tiqr?action=metadata&session=15573c09103054cd6e6ece5e81160ce2d514ce4b&serial=TiQR000264EC

```
{
  "identity": {
    "displayName": "Martijn Kruiten",
    "identifier": "martijk_2fa"
  },
  "service": {
    "authenticationUrl": "https://2fa.surfsara.nl/ttype/tiqr",
    "displayName": "SURF",
    "enrollmentUrl": "https://2fa.surfsara.nl/ttype/tiqr?action=enrollment&session=15573c09103054cd6e6ece5e81160ce2d514ce4b&serial=TiQR000264EC",
    "identifier": "nl.surf",
    "infoUrl": "https://surf.nl",
    "logoUrl": "https://userinfo.surfsara.nl/sites/all/themes/surfsara32/images/logo.png",
    "ocraSuite": "OCRA-1:HOTP-SHA1-6:QH10"
  },
  "signature": "rsa_sha256_pss:<obfuscated>"
}
```

**Comment by basvandervlies** [comment]
Ok we just bought a Nokia 5.1 with android one. Just install the TIQR app and the fingerprint works as expected also after deleting the account and enroll it. Tried it multiple times

**Comment by 7hommay** [comment]
Should be fixed in #42

**Comment by basvandervlies** [comment]
@7hommay thanks.

**Comment by Jaapdijkshoorn** [comment]
I have tested the develop branch and i can confirm that it works. How long will it take to get the fixed client in the app store?

**Comment by joostd** [comment]
Thanks, we will build a release next week and publish it using TestFlight. If there are no issues with our test scripts we can publish a production version in September.

**Comment by martijnkruiten** [comment]
With the newest release I still get the same error, although I can see that it's removing something before inserting:

```
Aug 30 14:02:20 iPhone-van-Martijn securityd[92] <Notice>: deleted <genp,rowid=61183,cdat=2019-08-30 11:38:32 +0000,mdat=2019-08-30 11:53:56 +0000,desc=null,icmt=null,crtr=null,type=null,scrp=null,labl=null,alis=null,invi=null,nega=null,cusi=null,prot=null,acct=martijk_2fa,svce=nl.surf,gena=null,data=07b8:070000000AF7040A...|a5f6895c2c976347,agrp=42GV37A67E.org.tiqr.surfnet,pdmn=ak,sync=0,tomb=0,sha1=58171B4ED23B4ED389F9C0B697FA7ED0522BE17A,vwht=null,tkid=null,v_Data=<?>,v_pk=BCF282D8E391B34509B05148BE9A876F1060486A,accc=310C300A0C0470726F740C02616B,u_Tomb=null,musr=,UUID=29B79A84-098A-479F-9C34-9E212A41D75A,sysb=null,pcss=null,pcsk=null,pcsi=null,persistref=> from <SecDbConnection rw open>
Aug 30 14:02:41 iPhone-van-Martijn securityd[92] <Notice>: inserted <genp,rowid=61262,cdat=2019-08-30 12:02:41 +0000,mdat=2019-08-30 12:02:41 +0000,desc=null,icmt=null,crtr=null,type=null,scrp=null,labl=null,alis=null,invi=null,nega=null,cusi=null,prot=null,acct=martijk_2fa,svce=nl.surf,gena=null,data=07b8:070000000AF7040A...|6292ae72a2ae0aac,agrp=42GV37A67E.org.tiqr.surfnet,pdmn=ak,sync=0,tomb=0,sha1=006E1A9D456AF8FF70A778B84E48A7A66B9F9A41,vwht=null,tkid=null,v_Data=<?>,v_pk=BCF282D8E391B34509B05148BE9A876F1060486A,accc=null,u_Tomb=null,musr=,UUID=489A8C4D-690F-4B13-83C6-C340BE514F46,sysb=null,pcss=null,pcsk=null,pcsi=null,persistref=>
Aug 30 14:02:41 iPhone-van-Martijn securityd[92] <Notice>: insert failed for item <genp,rowid=null,cdat=2019-08-30 12:02:41 +0000,mdat=2019-08-30 12:02:41 +0000,desc=null,icmt=null,crtr=null,type=null,scrp=null,labl=null,alis=null,invi=null,nega=null,cusi=null,prot=null,acct=martijk_2fa-biometric,svce=nl.surf,gena=null,data=07c2:070000000AF7040A...|3f21d69d9f40990a,agrp=42GV37A67E.org.tiqr.surfnet,pdmn=ak,sync=0,tomb=0,sha1=0E96E02A7CEEE3FDE27A5D31BCD2157F5CE07F7A,vwht=null,tkid=null,v_Data=<?>,v_pk=70D04D6F9AA326BA1F702CCECD604E74296CC9AA,accc=null,u_Tomb=null,musr=,UUID=6E394B0C-5F67-4A26-8569-C8E2CA3728A0,sysb=null,pcss=null,pcsk=null,pcsi=null,persistref=> with Error Domain=com.apple.utilities.sqlite3 Code=19 "finalize: 0x108688cd0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr" UserInfo={NSDescription=finalize: 0x108688cd0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr, NSUnderlyingError=0x107f02800 {Error Domain=com.apple.utilities.sqlite3 Co
```

If I delete the app and its data through Settings the issue still remains. It somehow keeps the database, or otherwise I can't explain what's happening here. Is there a way to force deletion of all related data so I can test it as if I was a new user?

**Comment by martijnkruiten** [comment]
It seems that it is deleting and then inserting `acct=martijk_2fa`, but it's not deleting `acct=martijk_2fa-biometric` before inserting it.

**Comment by 7hommay** [comment]
The data is stored in the iOS keychain, for which there no way to force deletion. 

Does the app itself present you with an error? Could you take me through the steps you made that resulted in the logs you shared?

**Comment by martijnkruiten** [comment]
Aha I see. The procedure to reproduce this issue:

1. Enroll a token and enable upgrade to Touch ID
2. Delete the token from the app
3. Repeat step one (same user, same server)

You will get the same issue as before when Bas opened this ticket. The app will tell give this error:

```
Account cannot be saved
Failed to generate identity secret. Please contact support.
```

The logs were gathered with `libimobiledevice` (specifically `idevicesyslog`). It seems that it's correctly removing the pin entry from the keychain before storing a new one, but not the biometric entry.
